### ISSUE TITLE
Access is being blocked by CORS policy

### ISSUE THREAD

**Issue by jakestrahm** [J-Obog/state-boundries#1]
![image](https://user-images.githubusercontent.com/46104507/138808298-2823ba74-7a01-4ee2-a7eb-04ddc8ebec3f.png)

**Comment by J-Obog** [comment]
Yea this was an issue with the server's CORS configuration (or lack thereof). The latest changes have been deployed so you can test it out now. Please let me know if there are any further issues.

**Comment by J-Obog** [comment]
Closing
